export const iceCreamFlavors = [
  {
    category: 'Chocolate',
    flavors: [
      'Chocolate',
      'Chocolate sureño',
      'Chocolate con almendras',
      'Chocolate relleno',
      'Chocolate con pasas',
      'Chocolate blanco',
      'Chocolate amargo',
    ],
  },
  {
    category: 'Dulce de leche',
    flavors: [
      'Dulce de leche',
      'Dulce de leche sureño',
      'Dulce de leche con nuez',
      'Dulce de leche con brownie',
      'Dulce de leche granizado',
      'Dulce de leche relleno',
      'Dulce de leche Cabsha',
    ],
  },
  {
    category: 'Frutales',
    flavors: [
      'Futilla',
      'Frambuesa',
      'Limón',
      'Durazno',
      'Ananá',
      'Twist de limón nuevo!',
      'Pomelo nuevo!',
    ],
  },
  {
    category: 'Cremas',
    flavors: [
      'Americana',
      'Vainilla',
      'Granizado',
      'Almendrado',
      'Rusa',
      'Flan con dulce',
      'Crema del cielo',
      'Sambayón',
      'Sambayón con almendras chocolatadas',
      'Tiramisú',
    ],
  },
  {
    category: 'Gourmet',
    flavors: [
      'Marroc',
      'Kinder',
      'Oreo',
      'Alfajor Grido',
      'Kinotos al whisky',
      'Frutilla a la reina',
      'Limón Glacé',
    ],
  },
  {
    category: 'Unicos Grido',
    flavors: [
      'Bananita dolca',
      'Sambayón Grido nuevo!',
      'Ferrero rocher',
      'Mantecol',
      'Tramontana',
      'Mascarpone con frutos del bosque',
    ],
  },
]
